# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20171124_2104'),
        ('bonus_records', '0002_auto_20171124_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_records', to='companies.Company'),
        ),
    ]
