# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_records', '0003_record_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
    ]
