# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:29
from __future__ import unicode_literals

import bonus_records.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_records', '0007_auto_20171203_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_records', to='companies.Company', validators=[bonus_records.validators.company_user_validation]),
        ),
    ]
