# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:36
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus_records', '0008_auto_20171203_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.contrib.auth.models.User, related_name='bonus_records', to='companies.Company'),
        ),
    ]
