# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companyinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinvite',
            name='accepted',
        ),
        migrations.AddField(
            model_name='companyinvite',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Accepted'), (2, 'Rejected')], default=0),
        ),
        migrations.AlterField(
            model_name='companyinvite',
            name='uuid',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
